### ISSUE TITLE
SCQL命令启动下 创建项目失败

### ISSUE THREAD

**Issue by Korano0521** [secretflow/secretnote#69]
在/secretnode/scql/project 页面下，创建项目时报错“No host provided.”
secretnode 启动命令：
secretnote scql <work_dir> --party=alice --broker=http://10.189.xxx.xxx:8080
alice broker为远端部署SCQL 0.9.1b1版本节点
secretnote报错日志如下：
400 POST 、api/broker?1733392668471 (127.0.0.1): no host provided.
wrote error: 'no host provided.'
    Traceback (most recent call last):
        File "/data/python_env/python_secretflow_nenv3.8/lib64/python3.8/site-packages/tornado/web.py", line 1790, in _execute
            result = await result
        File "/data/python_env/python_secretflow_nenv3.8/lib64/python3.8/site-packages/secretnote/server/services/broker/handlers.py", line 159, in post
            raise web.HTTPError(400, "no host provided.")

**Comment by zimu-yuxi** [comment]
scql的部署方式是什么？参考的哪个文档以及版本是什么？

**Comment by Korano0521** [comment]
P2P模式部署 alice/bob方均部署在阿里云ACK集群 通过SLB(loadbalance)暴露broker/engine服务端口 scql版本0.9.1b1
参考文档：
https://www.secretflow.org.cn/zh-CN/docs/scql/0.9.1b1/topics/deployment/how-to-deploy-p2p-cluster

**Comment by z0gSh1u** [comment]
Python 3.8下可能会装到旧版的SecretNote，其启动命令与当前版本不同，为

```
secretnote --mode=scql --party=alice --host=http://127.0.0.1:8991
```

如果可能建议升级Python到3.10，以使用更新后的SecretNote
```
requires-python = ">=3.10, <3.12"
```
